// Lista de palavras em português aprimorada para teste de digitação
export const portugueseWords = [
  'de', 'a', 'o', 'que', 'e', 'do', 'da', 'em', 'um', 'para', 'com', 'não', 'uma', 'os', 'no', 'se',
  'na', 'por', 'mais', 'as', 'dos', 'como', 'mas', 'foi', 'ao', 'ele', 'das', 'tem', 'à', 'seu', 'sua',
  'ou', 'ser', 'quando', 'muito', 'nos', 'já', 'está', 'eu', 'também', 'só', 'pelo', 'pela', 'até',
  'isso', 'ela', 'entre', 'era', 'depois', 'sem', 'mesmo', 'aos', 'ter', 'seus', 'quem', 'nas', 'me',
  'esse', 'eles', 'estão', 'você', 'tinha', 'foram', 'essa', 'num', 'nem', 'suas', 'meu', 'minha',
  'houve', 'qual', 'será', 'nós', 'tenho', 'lhe', 'deles', 'este', 'fosse', 'dele', 'vocês', 'nosso',
  'nossa', 'delas', 'esta', 'isto', 'aquilo', 'sobre', 'porque', 'sempre', 'casa', 'coisa', 'tempo',
  'dia', 'ano', 'vez', 'homem', 'trabalho', 'vida', 'governo', 'país', 'mundo', 'escola', 'empresa',
  'grupo', 'pessoa', 'mulher', 'parte', 'fato', 'caso', 'cidade', 'noite', 'hoje', 'ontem', 'amanhã',
  'agora', 'ainda', 'onde', 'assim', 'então', 'aqui', 'grande', 'pequeno', 'bom', 'mau', 'novo', 'velho',
  'alto', 'baixo', 'certo', 'errado', 'feliz', 'triste', 'fácil', 'difícil', 'claro', 'escuro', 'aberto',
  'fechado', 'quente', 'frio', 'primeiro', 'último', 'outro', 'próprio', 'verdadeiro', 'falso', 'melhor',
  'pior', 'maior', 'menor', 'poder', 'fazer', 'dizer', 'querer', 'saber', 'ver', 'dar', 'ficar', 'vir',
  'chegar', 'partir', 'sair', 'entrar', 'abrir', 'fechar', 'amar', 'gostar', 'precisar', 'ajudar',
  'estudar', 'brincar', 'correr', 'escrever', 'ler', 'cantar', 'dançar', 'viajar', 'conhecer', 'começar',
  'terminar', 'encontrar', 'perder', 'ganhar', 'pagar', 'receber', 'acreditar', 'mudar', 'manter',
  'sentir', 'ouvir', 'falar', 'pensar', 'lembrar', 'esquecer', 'coração', 'cabeça', 'corpo', 'mente',
  'alma', 'espírito', 'amor', 'paixão', 'amizade', 'família', 'filho', 'mãe', 'pai', 'irmão', 'amigo',
  'natureza', 'floresta', 'árvore', 'rio', 'mar', 'praia', 'sol', 'lua', 'estrela', 'céu', 'vento',
  'chuva', 'animal', 'cachorro', 'gato', 'pássaro', 'peixe', 'leão', 'tigre', 'elefante', 'macaco',
  'tecnologia', 'computador', 'internet', 'celular', 'aplicativo', 'programa', 'código', 'desenvolvimento',
  'futuro', 'passado', 'presente', 'história', 'ciência', 'arte', 'música', 'filme', 'livro', 'cultura',
  'educação', 'saúde', 'dinheiro', 'sucesso', 'felicidade', 'tristeza', 'medo', 'coragem', 'força',
  'esperança', 'sonho', 'realidade', 'problema', 'solução', 'ideia', 'criatividade', 'inteligência',
  'importante', 'interessante', 'diferente', 'especial', 'bonito', 'feio', 'incrível', 'maravilhoso',
  'excelente', 'ótimo', 'péssimo', 'rápido', 'lento', 'forte', 'fraco', 'jovem', 'criança', 'adulto',
  'atenção', 'endereço', 'explicação', 'informação', 'comunicação', 'organização', 'responsabilidade',
  'oportunidade', 'experiência', 'consequência', 'sustentabilidade', 'transformação', 'psicologia',
  'filosofia', 'sociologia', 'economia', 'política', 'democracia', 'liberdade', 'justiça', 'igualdade',
  'planeta', 'universo', 'galáxia', 'buraco', 'negro', 'matéria', 'energia', 'átomo', 'molécula',
  'caminho', 'estrada', 'ponte', 'edifício', 'janela', 'porta', 'parede', 'chão', 'teto', 'lâmpada',
  'conversa', 'silêncio', 'barulho', 'som', 'palavra', 'frase', 'texto', 'parágrafo', 'página', 'capítulo',
  'garrafa', 'copo', 'prato', 'faca', 'garfo', 'colher', 'comida', 'bebida', 'água', 'fome', 'sede'
];